# Generated by Django 4.2.3 on 2023-07-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_menuitem_reciperequirement_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.FloatField(max_length=10),
        ),
    ]
