# Generated by Django 4.2.3 on 2023-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_ingredient_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateField(),
        ),
    ]
