# Generated by Django 4.2.3 on 2023-07-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity_needed',
            field=models.IntegerField(max_length=5),
        ),
    ]
