# Generated by Django 4.2.3 on 2023-07-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_menuitem_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
    ]
