# Generated by Django 4.2.3 on 2023-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_menuitem_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity_needed',
            field=models.FloatField(),
        ),
    ]
