# Generated by Django 4.2.3 on 2023-07-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_menuitem_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
